In [2]:
import pandas as pd
import altair as alt

In [63]:
df = pd.read_csv("https://raw.githubusercontent.com/sj/covid19-excess-deaths-data/master/weekly-deaths.csv", sep=';', parse_dates=['first_day', 'last_day'])

df['first_day:year'] = df['first_day'].dt.year
df['first_day:yday'] = df['first_day'].dt.strftime('%j')

with pd.option_context('display.max_rows', 2000):
    display(df)

,country,first_day,last_day,filter,deaths,source,notes,first_day:year,first_day:yday
0,NL,1995-01-02,1995-01-08,NaN,2719,https://opendata.cbs.nl/statline/#/CBS/nl/data...,Previous week straddled two years and was skip...,1995,002
1,NL,1995-01-09,1995-01-15,NaN,2823,NaN,NaN,1995,009
2,NL,1995-01-16,1995-01-22,NaN,2609,NaN,NaN,1995,016
3,NL,1995-01-23,1995-01-29,NaN,2664,NaN,NaN,1995,023
4,NL,1995-01-30,1995-02-05,NaN,2577,NaN,NaN,1995,030
5,NL,1995-02-06,1995-02-12,NaN,2536,NaN,NaN,1995,037
6,NL,1995-02-13,1995-02-19,NaN,2551,NaN,NaN,1995,044
7,NL,1995-02-20,1995-02-26,NaN,2510,NaN,NaN,1995,051
8,NL,1995-02-27,1995-03-05,NaN,2490,NaN,NaN,1995,058
9,NL,1995-03-06,1995-03-12,NaN,2770,NaN,NaN,1995,065
10,NL,1995-03-13,1995-03-19,NaN,2800,NaN,NaN,1995,072
11,NL,1995-03-20,1995-03-26,NaN,2786,NaN,NaN,1995,079
12,NL,1995-03-27,1995-04-02,NaN,2634,NaN,NaN,1995,086
13,NL,1995-04-03,1995-04-09,NaN,2717,NaN,NaN,1995,093
14,NL,1995-04-10,1995-04-16,NaN,2645,NaN,NaN,1995,100
15,NL,1995-04-17,1995-04-23,NaN,2691,NaN,NaN,1995,107
16,NL,1995-04-24,1995-04-30,NaN,2645,NaN,NaN,1995,114
17,NL,1995-05-01,1995-05-07,NaN,2628,NaN,NaN,1995,121
18,NL,1995-05-08,1995-05-14,NaN,2486,NaN,NaN,1995,128
19,NL,1995-05-15,1995-05-21,NaN,2482,NaN,NaN,1995,135
20,NL,1995-05-22,1995-05-28,NaN,2468,NaN,NaN,1995,142
21,NL,1995-05-29,1995-06-04,NaN,2485,NaN,NaN,1995,149
22,NL,1995-06-05,1995-06-11,NaN,2319,NaN,NaN,1995,156
23,NL,1995-06-12,1995-06-18,NaN,2352,NaN,NaN,1995,163
24,NL,1995-06-19,1995-06-25,NaN,2498,NaN,NaN,1995,170
25,NL,1995-06-26,1995-07-02,NaN,2663,NaN,NaN,1995,177
26,NL,1995-07-03,1995-07-09,NaN,2489,NaN,NaN,1995,184
27,NL,1995-07-10,1995-07-16,NaN,2808,NaN,NaN,1995,191
28,NL,1995-07-17,1995-07-23,NaN,2451,NaN,NaN,1995,198
29,NL,1995-07-24,1995-07-30,NaN,2466,NaN,NaN,1995,205
30,NL,1995-07-31,1995-08-06,NaN,2744,NaN,NaN,1995,212
31,NL,1995-08-07,1995-08-13,NaN,2473,NaN,NaN,1995,219
32,NL,1995-08-14,1995-08-20,NaN,2380,NaN,NaN,1995,226
33,NL,1995-08-21,1995-08-27,NaN,2427,NaN,NaN,1995,233
34,NL,1995-08-28,1995-09-03,NaN,2278,NaN,NaN,1995,240
35,NL,1995-09-04,1995-09-10,NaN,2362,NaN,NaN,1995,247
36,NL,1995-09-11,1995-09-17,NaN,2348,NaN,NaN,1995,254
37,NL,1995-09-18,1995-09-24,NaN,2437,NaN,NaN,1995,261
38,NL,1995-09-25,1995-10-01,NaN,2366,NaN,NaN,1995,268
39,NL,1995-10-02,1995-10-08,NaN,2525,NaN,NaN,1995,275
40,NL,1995-10-09,1995-10-15,NaN,2600,NaN,NaN,1995,282
41,NL,1995-10-16,1995-10-22,NaN,2417,NaN,NaN,1995,289
42,NL,1995-10-23,1995-10-29,NaN,2455,NaN,NaN,1995,296
43,NL,1995-10-30,1995-11-05,NaN,2573,NaN,NaN,1995,303
44,NL,1995-11-06,1995-11-12,NaN,2533,NaN,NaN,1995,310
45,NL,1995-11-13,1995-11-19,NaN,2691,NaN,NaN,1995,317
46,NL,1995-11-20,1995-11-26,NaN,2613,NaN,NaN,1995,324
47,NL,1995-11-27,1995-12-03,NaN,2646,NaN,NaN,1995,331
48,NL,1995-12-04,1995-12-10,NaN,2826,NaN,NaN,1995,338
49,NL,1995-12-11,1995-12-17,NaN,3098,NaN,NaN,1995,345
50,NL,1995-12-18,1995-12-24,NaN,3291,NaN,NaN,1995,352
51,NL,1995-12-25,1995-12-31,NaN,3436,NaN,NaN,1995,359
52,NL,1996-01-01,1996-01-07,NaN,3546,NaN,NaN,1996,001
53,NL,1996-01-08,1996-01-14,NaN,3257,NaN,NaN,1996,008
54,NL,1996-01-15,1996-01-21,NaN,2970,NaN,NaN,1996,015
55,NL,1996-01-22,1996-01-28,NaN,2855,NaN,NaN,1996,022
56,NL,1996-01-29,1996-02-04,NaN,2992,NaN,NaN,1996,029
57,NL,1996-02-05,1996-02-11,NaN,3089,NaN,NaN,1996,036
58,NL,1996-02-12,1996-02-18,NaN,3046,NaN,NaN,1996,043
59,NL,1996-02-19,1996-02-25,NaN,2887,NaN,NaN,1996,050
60,NL,1996-02-26,1996-03-03,NaN,2878,NaN,NaN,1996,057
61,NL,1996-03-04,1996-03-10,NaN,2714,NaN,NaN,1996,064
62,NL,1996-03-11,1996-03-17,NaN,2807,NaN,NaN,1996,071
63,NL,1996-03-18,1996-03-24,NaN,2784,NaN,NaN,1996,078
64,NL,1996-03-25,1996-03-31,NaN,2727,NaN,NaN,1996,085
65,NL,1996-04-01,1996-04-07,NaN,2765,NaN,NaN,1996,092
66,NL,1996-04-08,1996-04-14,NaN,2642,NaN,NaN,1996,099
67,NL,1996-04-15,1996-04-21,NaN,2856,NaN,NaN,1996,106
68,NL,1996-04-22,1996-04-28,NaN,2703,NaN,NaN,1996,113
69,NL,1996-04-29,1996-05-05,NaN,2498,NaN,NaN,1996,120
70,NL,1996-05-06,1996-05-12,NaN,2519,NaN,NaN,1996,127
71,NL,1996-05-13,1996-05-19,NaN,2598,NaN,NaN,1996,134
72,NL,1996-05-20,1996-05-26,NaN,2514,NaN,NaN,1996,141
73,NL,1996-05-27,1996-06-02,NaN,2523,NaN,NaN,1996,148
74,NL,1996-06-03,1996-06-09,NaN,2752,NaN,NaN,1996,155
75,NL,1996-06-10,1996-06-16,NaN,2506,NaN,NaN,1996,162
76,NL,1996-06-17,1996-06-23,NaN,2366,NaN,NaN,1996,169
77,NL,1996-06-24,1996-06-30,NaN,2376,NaN,NaN,1996,176
78,NL,1996-07-01,1996-07-07,NaN,2433,NaN,NaN,1996,183
79,NL,1996-07-08,1996-07-14,NaN,2490,NaN,NaN,1996,190
80,NL,1996-07-15,1996-07-21,NaN,2467,NaN,NaN,1996,197
81,NL,1996-07-22,1996-07-28,NaN,2500,NaN,NaN,1996,204
82,NL,1996-07-29,1996-08-04,NaN,2285,NaN,NaN,1996,211
83,NL,1996-08-05,1996-08-11,NaN,2449,NaN,NaN,1996,218
84,NL,1996-08-12,1996-08-18,NaN,2357,NaN,NaN,1996,225
85,NL,1996-08-19,1996-08-25,NaN,2364,NaN,NaN,1996,232
86,NL,1996-08-26,1996-09-01,NaN,2273,NaN,NaN,1996,239
87,NL,1996-09-02,1996-09-08,NaN,2150,NaN,NaN,1996,246
88,NL,1996-09-09,1996-09-15,NaN,2275,NaN,NaN,1996,253
89,NL,1996-09-16,1996-09-22,NaN,2523,NaN,NaN,1996,260
90,NL,1996-09-23,1996-09-29,NaN,2582,NaN,NaN,1996,267
91,NL,1996-09-30,1996-10-06,NaN,2467,NaN,NaN,1996,274
92,NL,1996-10-07,1996-10-13,NaN,2417,NaN,NaN,1996,281
93,NL,1996-10-14,1996-10-20,NaN,2377,NaN,NaN,1996,288
94,NL,1996-10-21,1996-10-27,NaN,2465,NaN,NaN,1996,295
95,NL,1996-10-28,1996-11-03,NaN,2404,NaN,NaN,1996,302
96,NL,1996-11-04,1996-11-10,NaN,2513,NaN,NaN,1996,309
97,NL,1996-11-11,1996-11-17,NaN,2537,NaN,NaN,1996,316
98,NL,1996-11-18,1996-11-24,NaN,2636,NaN,NaN,1996,323
99,NL,1996-11-25,1996-12-01,NaN,2591,NaN,NaN,1996,330
100,NL,1996-12-02,1996-12-08,NaN,2604,NaN,NaN,1996,337
101,NL,1996-12-09,1996-12-15,NaN,2708,NaN,NaN,1996,344
102,NL,1996-12-16,1996-12-22,NaN,2773,NaN,NaN,1996,351
103,NL,1996-12-23,1996-12-29,NaN,2893,NaN,NaN,1996,358
104,NL,1997-01-06,1997-01-12,NaN,3290,NaN,Previous week (1997-W1) straddles two years an...,1997,006
105,NL,1997-01-13,1997-01-19,NaN,3249,NaN,NaN,1997,013
106,NL,1997-01-20,1997-01-26,NaN,3185,NaN,NaN,1997,020
107,NL,1997-01-27,1997-02-02,NaN,3061,NaN,NaN,1997,027
108,NL,1997-02-03,1997-02-09,NaN,3012,NaN,NaN,1997,034
109,NL,1997-02-10,1997-02-16,NaN,2980,NaN,NaN,1997,041
110,NL,1997-02-17,1997-02-23,NaN,2807,NaN,NaN,1997,048
111,NL,1997-02-24,1997-03-02,NaN,2792,NaN,NaN,1997,055
112,NL,1997-03-03,1997-03-09,NaN,2640,NaN,NaN,1997,062
113,NL,1997-03-10,1997-03-16,NaN,2529,NaN,NaN,1997,069
114,NL,1997-03-17,1997-03-23,NaN,2467,NaN,NaN,1997,076
115,NL,1997-03-24,1997-03-30,NaN,2483,NaN,NaN,1997,083
116,NL,1997-03-31,1997-04-06,NaN,2546,NaN,NaN,1997,090
117,NL,1997-04-07,1997-04-13,NaN,2451,NaN,NaN,1997,097
118,NL,1997-04-14,1997-04-20,NaN,2455,NaN,NaN,1997,104
119,NL,1997-04-21,1997-04-27,NaN,2649,NaN,NaN,1997,111
120,NL,1997-04-28,1997-05-04,NaN,2646,NaN,NaN,1997,118
121,NL,1997-05-05,1997-05-11,NaN,2437,NaN,NaN,1997,125
122,NL,1997-05-12,1997-05-18,NaN,2611,NaN,NaN,1997,132
123,NL,1997-05-19,1997-05-25,NaN,2483,NaN,NaN,1997,139
124,NL,1997-05-26,1997-06-01,NaN,2426,NaN,NaN,1997,146
125,NL,1997-06-02,1997-06-08,NaN,2709,NaN,NaN,1997,153
126,NL,1997-06-09,1997-06-15,NaN,2555,NaN,NaN,1997,160
127,NL,1997-06-16,1997-06-22,NaN,2391,NaN,NaN,1997,167
128,NL,1997-06-23,1997-06-29,NaN,2372,NaN,NaN,1997,174
129,NL,1997-06-30,1997-07-06,NaN,2409,NaN,NaN,1997,181
130,NL,1997-07-07,1997-07-13,NaN,2486,NaN,NaN,1997,188
131,NL,1997-07-14,1997-07-20,NaN,2402,NaN,NaN,1997,195
132,NL,1997-07-21,1997-07-27,NaN,2369,NaN,NaN,1997,202
133,NL,1997-07-28,1997-08-03,NaN,2352,NaN,NaN,1997,209
134,NL,1997-08-04,1997-08-10,NaN,2434,NaN,NaN,1997,216
135,NL,1997-08-11,1997-08-17,NaN,2943,NaN,NaN,1997,223
136,NL,1997-08-18,1997-08-24,NaN,2809,NaN,NaN,1997,230
137,NL,1997-08-25,1997-08-31,NaN,2488,NaN,NaN,1997,237
138,NL,1997-09-01,1997-09-07,NaN,2307,NaN,NaN,1997,244
139,NL,1997-09-08,1997-09-14,NaN,2402,NaN,NaN,1997,251
140,NL,1997-09-15,1997-09-21,NaN,2433,NaN,NaN,1997,258
141,NL,1997-09-22,1997-09-28,NaN,2360,NaN,NaN,1997,265
142,NL,1997-09-29,1997-10-05,NaN,2386,NaN,NaN,1997,272
143,NL,1997-10-06,1997-10-12,NaN,2557,NaN,NaN,1997,279
144,NL,1997-10-13,1997-10-19,NaN,2441,NaN,NaN,1997,286
145,NL,1997-10-20,1997-10-26,NaN,2549,NaN,NaN,1997,293
146,NL,1997-10-27,1997-11-02,NaN,2450,NaN,NaN,1997,300
147,NL,1997-11-03,1997-11-09,NaN,2530,NaN,NaN,1997,307
148,NL,1997-11-10,1997-11-16,NaN,2408,NaN,NaN,1997,314
149,NL,1997-11-17,1997-11-23,NaN,2446,NaN,NaN,1997,321
150,NL,1997-11-24,1997-11-30,NaN,2663,NaN,NaN,1997,328
151,NL,1997-12-01,1997-12-07,NaN,2538,NaN,NaN,1997,335
152,NL,1997-12-08,1997-12-14,NaN,2670,NaN,NaN,1997,342
153,NL,1997-12-15,1997-12-21,NaN,2738,NaN,NaN,1997,349
154,NL,1997-12-22,1997-12-28,NaN,2595,NaN,NaN,1997,356
155,NL,1998-01-05,1998-01-11,NaN,2558,NaN,Previous week (1998-W1) straddles two years an...,1998,005
156,NL,1998-01-12,1998-01-18,NaN,2418,NaN,NaN,1998,012
157,NL,1998-01-19,1998-01-25,NaN,2530,NaN,NaN,1998,019
158,NL,1998-01-26,1998-02-01,NaN,2691,NaN,NaN,1998,026
159,NL,1998-02-02,1998-02-08,NaN,2615,NaN,NaN,1998,033
160,NL,1998-02-09,1998-02-15,NaN,2695,NaN,NaN,1998,040
161,NL,1998-02-16,1998-02-22,NaN,2719,NaN,NaN,1998,047
162,NL,1998-02-23,1998-03-01,NaN,2627,NaN,NaN,1998,054
163,NL,1998-03-02,1998-03-08,NaN,2812,NaN,NaN,1998,061
164,NL,1998-03-09,1998-03-15,NaN,2876,NaN,NaN,1998,068
165,NL,1998-03-16,1998-03-22,NaN,2991,NaN,NaN,1998,075
166,NL,1998-03-23,1998-03-29,NaN,2984,NaN,NaN,1998,082
167,NL,1998-03-30,1998-04-05,NaN,3107,NaN,NaN,1998,089
168,NL,1998-04-06,1998-04-12,NaN,2910,NaN,NaN,1998,096
169,NL,1998-04-13,1998-04-19,NaN,2900,NaN,NaN,1998,103
170,NL,1998-04-20,1998-04-26,NaN,2768,NaN,NaN,1998,110
171,NL,1998-04-27,1998-05-03,NaN,2692,NaN,NaN,1998,117
172,NL,1998-05-04,1998-05-10,NaN,2598,NaN,NaN,1998,124
173,NL,1998-05-11,1998-05-17,NaN,2826,NaN,NaN,1998,131
174,NL,1998-05-18,1998-05-24,NaN,2588,NaN,NaN,1998,138
175,NL,1998-05-25,1998-05-31,NaN,2505,NaN,NaN,1998,145
176,NL,1998-06-01,1998-06-07,NaN,2368,NaN,NaN,1998,152
177,NL,1998-06-08,1998-06-14,NaN,2383,NaN,NaN,1998,159
178,NL,1998-06-15,1998-06-21,NaN,2545,NaN,NaN,1998,166
179,NL,1998-06-22,1998-06-28,NaN,2456,NaN,NaN,1998,173
180,NL,1998-06-29,1998-07-05,NaN,2451,NaN,NaN,1998,180
181,NL,1998-07-06,1998-07-12,NaN,2456,NaN,NaN,1998,187
182,NL,1998-07-13,1998-07-19,NaN,2408,NaN,NaN,1998,194
183,NL,1998-07-20,1998-07-26,NaN,2588,NaN,NaN,1998,201
184,NL,1998-07-27,1998-08-02,NaN,2409,NaN,NaN,1998,208
185,NL,1998-08-03,1998-08-09,NaN,2450,NaN,NaN,1998,215
186,NL,1998-08-10,1998-08-16,NaN,2514,NaN,NaN,1998,222
187,NL,1998-08-17,1998-08-23,NaN,2399,NaN,NaN,1998,229
188,NL,1998-08-24,1998-08-30,NaN,2343,NaN,NaN,1998,236
189,NL,1998-08-31,1998-09-06,NaN,2478,NaN,NaN,1998,243
190,NL,1998-09-07,1998-09-13,NaN,2430,NaN,NaN,1998,250
191,NL,1998-09-14,1998-09-20,NaN,2496,NaN,NaN,1998,257
192,NL,1998-09-21,1998-09-27,NaN,2524,NaN,NaN,1998,264
193,NL,1998-09-28,1998-10-04,NaN,2471,NaN,NaN,1998,271
194,NL,1998-10-05,1998-10-11,NaN,2484,NaN,NaN,1998,278
195,NL,1998-10-12,1998-10-18,NaN,2623,NaN,NaN,1998,285
196,NL,1998-10-19,1998-10-25,NaN,2537,NaN,NaN,1998,292
197,NL,1998-10-26,1998-11-01,NaN,2453,NaN,NaN,1998,299
198,NL,1998-11-02,1998-11-08,NaN,2570,NaN,NaN,1998,306
199,NL,1998-11-09,1998-11-15,NaN,2621,NaN,NaN,1998,313
200,NL,1998-11-16,1998-11-22,NaN,2697,NaN,NaN,1998,320
201,NL,1998-11-23,1998-11-29,NaN,2713,NaN,NaN,1998,327
202,NL,1998-11-30,1998-12-06,NaN,2866,NaN,NaN,1998,334
203,NL,1998-12-07,1998-12-13,NaN,3034,NaN,NaN,1998,341
204,NL,1998-12-14,1998-12-20,NaN,3058,NaN,NaN,1998,348
205,NL,1998-12-21,1998-12-27,NaN,2964,NaN,NaN,1998,355
206,NL,1999-01-04,1999-01-10,NaN,3106,NaN,Previous week straddled two years and was skip...,1999,004
207,NL,1999-01-11,1999-01-17,NaN,3005,NaN,NaN,1999,011
208,NL,1999-01-18,1999-01-24,NaN,2918,NaN,NaN,1999,018
209,NL,1999-01-25,1999-01-31,NaN,2866,NaN,NaN,1999,025
210,NL,1999-02-01,1999-02-07,NaN,2972,NaN,NaN,1999,032
211,NL,1999-02-08,1999-02-14,NaN,3105,NaN,NaN,1999,039
212,NL,1999-02-15,1999-02-21,NaN,3123,NaN,NaN,1999,046
213,NL,1999-02-22,1999-02-28,NaN,3134,NaN,NaN,1999,053
214,NL,1999-03-01,1999-03-07,NaN,3241,NaN,NaN,1999,060
215,NL,1999-03-08,1999-03-14,NaN,3078,NaN,NaN,1999,067
216,NL,1999-03-15,1999-03-21,NaN,2797,NaN,NaN,1999,074
217,NL,1999-03-22,1999-03-28,NaN,2824,NaN,NaN,1999,081
218,NL,1999-03-29,1999-04-04,NaN,2713,NaN,NaN,1999,088
219,NL,1999-04-05,1999-04-11,NaN,2671,NaN,NaN,1999,095
220,NL,1999-04-12,1999-04-18,NaN,2533,NaN,NaN,1999,102
221,NL,1999-04-19,1999-04-25,NaN,2646,NaN,NaN,1999,109
222,NL,1999-04-26,1999-05-02,NaN,2636,NaN,NaN,1999,116
223,NL,1999-05-03,1999-05-09,NaN,2674,NaN,NaN,1999,123
224,NL,1999-05-10,1999-05-16,NaN,2507,NaN,NaN,1999,130
225,NL,1999-05-17,1999-05-23,NaN,2589,NaN,NaN,1999,137
226,NL,1999-05-24,1999-05-30,NaN,2561,NaN,NaN,1999,144
227,NL,1999-05-31,1999-06-06,NaN,2534,NaN,NaN,1999,151
228,NL,1999-06-07,1999-06-13,NaN,2575,NaN,NaN,1999,158
229,NL,1999-06-14,1999-06-20,NaN,2583,NaN,NaN,1999,165
230,NL,1999-06-21,1999-06-27,NaN,2462,NaN,NaN,1999,172
231,NL,1999-06-28,1999-07-04,NaN,2630,NaN,NaN,1999,179
232,NL,1999-07-05,1999-07-11,NaN,2485,NaN,NaN,1999,186
233,NL,1999-07-12,1999-07-18,NaN,2611,NaN,NaN,1999,193
234,NL,1999-07-19,1999-07-25,NaN,2548,NaN,NaN,1999,200
235,NL,1999-07-26,1999-08-01,NaN,2486,NaN,NaN,1999,207
236,NL,1999-08-02,1999-08-08,NaN,2753,NaN,NaN,1999,214
237,NL,1999-08-09,1999-08-15,NaN,2452,NaN,NaN,1999,221
238,NL,1999-08-16,1999-08-22,NaN,2450,NaN,NaN,1999,228
239,NL,1999-08-23,1999-08-29,NaN,2571,NaN,NaN,1999,235
240,NL,1999-08-30,1999-09-05,NaN,2459,NaN,NaN,1999,242
241,NL,1999-09-06,1999-09-12,NaN,2501,NaN,NaN,1999,249
242,NL,1999-09-13,1999-09-19,NaN,2527,NaN,NaN,1999,256
243,NL,1999-09-20,1999-09-26,NaN,2497,NaN,NaN,1999,263
244,NL,1999-09-27,1999-10-03,NaN,2458,NaN,NaN,1999,270
245,NL,1999-10-04,1999-10-10,NaN,2335,NaN,NaN,1999,277
246,NL,1999-10-11,1999-10-17,NaN,2403,NaN,NaN,1999,284
247,NL,1999-10-18,1999-10-24,NaN,2631,NaN,NaN,1999,291
248,NL,1999-10-25,1999-10-31,NaN,2663,NaN,NaN,1999,298
249,NL,1999-11-01,1999-11-07,NaN,2565,NaN,NaN,1999,305
250,NL,1999-11-08,1999-11-14,NaN,2583,NaN,NaN,1999,312
251,NL,1999-11-15,1999-11-21,NaN,2571,NaN,NaN,1999,319
252,NL,1999-11-22,1999-11-28,NaN,2631,NaN,NaN,1999,326
253,NL,1999-11-29,1999-12-05,NaN,2618,NaN,NaN,1999,333
254,NL,1999-12-06,1999-12-12,NaN,2791,NaN,NaN,1999,340
255,NL,1999-12-13,1999-12-19,NaN,2885,NaN,NaN,1999,347
256,NL,1999-12-20,1999-12-26,NaN,2974,NaN,NaN,1999,354
257,NL,2000-01-03,2000-01-09,NaN,3564,NaN,Previous week straddled two years and was skip...,2000,003
258,NL,2000-01-10,2000-01-16,NaN,3438,NaN,NaN,2000,010
259,NL,2000-01-17,2000-01-23,NaN,3307,NaN,NaN,2000,017
260,NL,2000-01-24,2000-01-30,NaN,3203,NaN,NaN,2000,024
261,NL,2000-01-31,2000-02-06,NaN,2967,NaN,NaN,2000,031
262,NL,2000-02-07,2000-02-13,NaN,2835,NaN,NaN,2000,038
263,NL,2000-02-14,2000-02-20,NaN,2773,NaN,NaN,2000,045
264,NL,2000-02-21,2000-02-27,NaN,2869,NaN,NaN,2000,052
265,NL,2000-02-28,2000-03-05,NaN,2673,NaN,NaN,2000,059
266,NL,2000-03-06,2000-03-12,NaN,2690,NaN,NaN,2000,066
267,NL,2000-03-13,2000-03-19,NaN,2673,NaN,NaN,2000,073
268,NL,2000-03-20,2000-03-26,NaN,2533,NaN,NaN,2000,080
269,NL,2000-03-27,2000-04-02,NaN,2554,NaN,NaN,2000,087
270,NL,2000-04-03,2000-04-09,NaN,2690,NaN,NaN,2000,094
271,NL,2000-04-10,2000-04-16,NaN,2687,NaN,NaN,2000,101
272,NL,2000-04-17,2000-04-23,NaN,2705,NaN,NaN,2000,108
273,NL,2000-04-24,2000-04-30,NaN,2647,NaN,NaN,2000,115
274,NL,2000-05-01,2000-05-07,NaN,2554,NaN,NaN,2000,122
275,NL,2000-05-08,2000-05-14,NaN,2744,NaN,NaN,2000,129
276,NL,2000-05-15,2000-05-21,NaN,2698,NaN,NaN,2000,136
277,NL,2000-05-22,2000-05-28,NaN,2455,NaN,NaN,2000,143
278,NL,2000-05-29,2000-06-04,NaN,2513,NaN,NaN,2000,150
279,NL,2000-06-05,2000-06-11,NaN,2484,NaN,NaN,2000,157
280,NL,2000-06-12,2000-06-18,NaN,2452,NaN,NaN,2000,164
281,NL,2000-06-19,2000-06-25,NaN,2969,NaN,NaN,2000,171
282,NL,2000-06-26,2000-07-02,NaN,2632,NaN,NaN,2000,178
283,NL,2000-07-03,2000-07-09,NaN,2572,NaN,NaN,2000,185
284,NL,2000-07-10,2000-07-16,NaN,2469,NaN,NaN,2000,192
285,NL,2000-07-17,2000-07-23,NaN,2456,NaN,NaN,2000,199
286,NL,2000-07-24,2000-07-30,NaN,2505,NaN,NaN,2000,206
287,NL,2000-07-31,2000-08-06,NaN,2532,NaN,NaN,2000,213
288,NL,2000-08-07,2000-08-13,NaN,2488,NaN,NaN,2000,220
289,NL,2000-08-14,2000-08-20,NaN,2539,NaN,NaN,2000,227
290,NL,2000-08-21,2000-08-27,NaN,2416,NaN,NaN,2000,234
291,NL,2000-08-28,2000-09-03,NaN,2391,NaN,NaN,2000,241
292,NL,2000-09-04,2000-09-10,NaN,2506,NaN,NaN,2000,248
293,NL,2000-09-11,2000-09-17,NaN,2517,NaN,NaN,2000,255
294,NL,2000-09-18,2000-09-24,NaN,2501,NaN,NaN,2000,262
295,NL,2000-09-25,2000-10-01,NaN,2479,NaN,NaN,2000,269
296,NL,2000-10-02,2000-10-08,NaN,2578,NaN,NaN,2000,276
297,NL,2000-10-09,2000-10-15,NaN,2539,NaN,NaN,2000,283
298,NL,2000-10-16,2000-10-22,NaN,2571,NaN,NaN,2000,290
299,NL,2000-10-23,2000-10-29,NaN,2734,NaN,NaN,2000,297
300,NL,2000-10-30,2000-11-05,NaN,2652,NaN,NaN,2000,304
301,NL,2000-11-06,2000-11-12,NaN,2572,NaN,NaN,2000,311
302,NL,2000-11-13,2000-11-19,NaN,2644,NaN,NaN,2000,318
303,NL,2000-11-20,2000-11-26,NaN,2689,NaN,NaN,2000,325
304,NL,2000-11-27,2000-12-03,NaN,2773,NaN,NaN,2000,332
305,NL,2000-12-04,2000-12-10,NaN,2618,NaN,NaN,2000,339
306,NL,2000-12-11,2000-12-17,NaN,2737,NaN,NaN,2000,346
307,NL,2000-12-18,2000-12-24,NaN,2855,NaN,NaN,2000,353
308,NL,2000-12-25,2000-12-31,NaN,2929,NaN,NaN,2000,360
309,NL,2001-01-01,2001-01-07,NaN,3051,NaN,NaN,2001,001
310,NL,2001-01-08,2001-01-14,NaN,2852,NaN,NaN,2001,008
311,NL,2001-01-15,2001-01-21,NaN,2907,NaN,NaN,2001,015
312,NL,2001-01-22,2001-01-28,NaN,3031,NaN,NaN,2001,022
313,NL,2001-01-29,2001-02-04,NaN,2928,NaN,NaN,2001,029
314,NL,2001-02-05,2001-02-11,NaN,2861,NaN,NaN,2001,036
315,NL,2001-02-12,2001-02-18,NaN,2761,NaN,NaN,2001,043
316,NL,2001-02-19,2001-02-25,NaN,2685,NaN,NaN,2001,050
317,NL,2001-02-26,2001-03-04,NaN,2749,NaN,NaN,2001,057
318,NL,2001-03-05,2001-03-11,NaN,2896,NaN,NaN,2001,064
319,NL,2001-03-12,2001-03-18,NaN,2812,NaN,NaN,2001,071
320,NL,2001-03-19,2001-03-25,NaN,2837,NaN,NaN,2001,078
321,NL,2001-03-26,2001-04-01,NaN,2774,NaN,NaN,2001,085
322,NL,2001-04-02,2001-04-08,NaN,2794,NaN,NaN,2001,092
323,NL,2001-04-09,2001-04-15,NaN,2752,NaN,NaN,2001,099
324,NL,2001-04-16,2001-04-22,NaN,2590,NaN,NaN,2001,106
325,NL,2001-04-23,2001-04-29,NaN,2712,NaN,NaN,2001,113
326,NL,2001-04-30,2001-05-06,NaN,2685,NaN,NaN,2001,120
327,NL,2001-05-07,2001-05-13,NaN,2739,NaN,NaN,2001,127
328,NL,2001-05-14,2001-05-20,NaN,2759,NaN,NaN,2001,134
329,NL,2001-05-21,2001-05-27,NaN,2674,NaN,NaN,2001,141
330,NL,2001-05-28,2001-06-03,NaN,2722,NaN,NaN,2001,148
331,NL,2001-06-04,2001-06-10,NaN,2581,NaN,NaN,2001,155
332,NL,2001-06-11,2001-06-17,NaN,2721,NaN,NaN,2001,162
333,NL,2001-06-18,2001-06-24,NaN,2585,NaN,NaN,2001,169
334,NL,2001-06-25,2001-07-01,NaN,2683,NaN,NaN,2001,176
335,NL,2001-07-02,2001-07-08,NaN,2751,NaN,NaN,2001,183
336,NL,2001-07-09,2001-07-15,NaN,2475,NaN,NaN,2001,190
337,NL,2001-07-16,2001-07-22,NaN,2405,NaN,NaN,2001,197
338,NL,2001-07-23,2001-07-29,NaN,2519,NaN,NaN,2001,204
339,NL,2001-07-30,2001-08-05,NaN,2438,NaN,NaN,2001,211
340,NL,2001-08-06,2001-08-12,NaN,2450,NaN,NaN,2001,218
341,NL,2001-08-13,2001-08-19,NaN,2511,NaN,NaN,2001,225
342,NL,2001-08-20,2001-08-26,NaN,2648,NaN,NaN,2001,232
343,NL,2001-08-27,2001-09-02,NaN,2441,NaN,NaN,2001,239
344,NL,2001-09-03,2001-09-09,NaN,2482,NaN,NaN,2001,246
345,NL,2001-09-10,2001-09-16,NaN,2403,NaN,NaN,2001,253
346,NL,2001-09-17,2001-09-23,NaN,2577,NaN,NaN,2001,260
347,NL,2001-09-24,2001-09-30,NaN,2588,NaN,NaN,2001,267
348,NL,2001-10-01,2001-10-07,NaN,2607,NaN,NaN,2001,274
349,NL,2001-10-08,2001-10-14,NaN,2567,NaN,NaN,2001,281
350,NL,2001-10-15,2001-10-21,NaN,2701,NaN,NaN,2001,288
351,NL,2001-10-22,2001-10-28,NaN,2568,NaN,NaN,2001,295
352,NL,2001-10-29,2001-11-04,NaN,2519,NaN,NaN,2001,302
353,NL,2001-11-05,2001-11-11,NaN,2535,NaN,NaN,2001,309
354,NL,2001-11-12,2001-11-18,NaN,2674,NaN,NaN,2001,316
355,NL,2001-11-19,2001-11-25,NaN,2749,NaN,NaN,2001,323
356,NL,2001-11-26,2001-12-02,NaN,2757,NaN,NaN,2001,330
357,NL,2001-12-03,2001-12-09,NaN,2768,NaN,NaN,2001,337
358,NL,2001-12-10,2001-12-16,NaN,2797,NaN,NaN,2001,344

In [56]:
alt.Chart(df).mark_line().encode(
    alt.X('first_day:yday', type='temporal', title='week (starting)'),
    alt.Y('deaths', type='quantitative', title='number of deaths'),
    color='first_day:year:O'
).interactive() #.add_selection(alt.selection_interval(bind='scales'))

#band = alt.Chart(df).mark_errorband(extent='ci').encode(
#    x = 'first_day',
#    y = 'deaths'
#)

#line + band

alt.Chart(...)